# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: SFTP uploader
          # You may pin to the exact commit or the version.
          # uses: wangyucode/sftp-upload-action@24f8bb83383dc39bed201ee5da01475e6c38c568
        uses: wangyucode/sftp-upload-action@v1.1
        with:
          # 
          host: sftp://nawidslr.com
          # 
          port: # optional, default is 22
          # 
          username: nawi01
          # 
          password: Unesco1507
          # 
          localDir: 
          # 
          remoteDir: /public_html/JLR7/
          # 
          dryRun: # optional
